export declare enum IOrderStatus {
    Pending = "Pending",
    AwaitingPayment = "Awaiting Payment",
    AwaitingFulfillment = "Awaiting Fulfillment",
    OrderConfirmed = "Order Confirmed",
    AwaitingShipment = "Awaiting Shipment",
    PartiallShipped = "Partiall Shipped",
    Shipped = "Shipped",
    AwaitingPickup = "Awaiting Pickup",
    Picked = "Picked",
    OutForDelivery = "Out For Delivery",
    Delivered = "Delivered",
    Completed = "Completed",
    Success = "Success",
    Failed = "Failed",
    RefundRequest = "Refund Request",
    InitiateRefund = "Initiate Refund",
    Cancelled = "Cancelled",
    Declined = "Declined",
    Refunded = "Refunded",
    Disputed = "Disputed",
    PartiallyRefunded = "Partially Refunded",
    PaymentFailed = "Payment Failed"
}
